from superpipe import pipes
import sys
sys.path.append('src')
from helpers import *
# from seqlib import *
# from extensions import *
from graphlib import mergeOrderedSeqs
from seq2graph import Seq2Graph

@pipes
class chap2:

# 1.3.3 Genome Path Problem
if run(3):
   s = parseSeqsStr('ACCGA CCGAA CGAAG GAAGC AAGCT')
   mergeOrderedSeqs(s) >> testVs('ACCGAAGCT')
if run(4):
   readlines('dataset_198_3.txt') >> mergeOrderedSeqs >> testVs('AACTGCGGGTTTATGTGTGTGCGGGGCGAGTCATGTGAATCCGGACCTAACCGTTCCTGCCAGATATGATCTTAGCCAAGAAAAGTAATTGGGGCCTGGGCGGGAGTAAGTCTTACATACACGTCCACGGTCCATGCTGCCGCCGTCGTAATTTTTAGGTCGCCTATTATATGATGAGAATCACCTCACGTAATAAGGTTGTTATCGTATACTCAAGGGAAACTGACCGTGGGACCAACGTGTCTGAGCCGCATAAATGTATCACAGCCAGCGGGGTATTTGCCTACTCGCCGCTTCGCTAGTGCGCTACTGGTGTCACTCATTAAAGCCACCGGATGGGGCGCTTGAGTGGGTCCGTTCGCCAAAGTAACGTTGCCTAACTCCCACTGAATAGGAGTAGAACTGCACAGTAATGAGATGCTTCGGGCCGATCTCAATCATGACCCTCTAATATAGGGTTGGAATAATTAACCCAGAACCACTTGAGCGAACGGCTATTTCCGCAGGTAGGTCATATTCACGACAGAATAAGTGGACTTTCATGTGAGCGTGGAAATGGCTATCTTCGTGGTCAAGTGGCCTCCTGCGGAGGAGCATAGCCCCCGCTTACCCAAAAATTTCAGCTACTGTCCGACAGGCCCCTTCATCAGGCCTACCTGTTGATCTTTACAAGACTTCATCTCTGCTTAGATGCTTTCACGCCTCTGCAGAGATGTAAAGCGCCAAGTTGCACTCGTTTACAGCGACTTCATAAGTCCTGTATGCCGTGCGGAGCCCACGTTTATCTACTGGAACAACCTCTCGACGGCAATTCAATGAAATAAACAACGTAGAGCGATACGTCGAGGGCCATATGTCAACCTAACACAACATTATCCAACAAGATATCCTTATGTCGCAACGCAAAAGGGGGGAGTCCTTCGAAGTCTTTAATGCCTCGTCATTGTGGCACTTCACCAGCCTTCAGGATGGCTTTCGAGCTATTTCGTTGACGGGCACGAAGTAGCGGTGCCGTCAGAAAACACTCCGTTAGTACCGAAATAGTGGCACACAGGCCAGCAGGGCGTTTTCATATTTCACTTCAACCAGAGACACTTAGCCGGGCGCTAGTCGCGGTTGACAAACTGTCCCTCCTAGAAGTTTGCCCCACAAAGGGAGCCACGATCGTTCAGGTGAAATCGAAATAACGAAGCTTGATTTCATCGGCCGAGAAGCTGATGCGCACGTGGAGCGGCACGAAGACAATTAAAACAGCCACGGTGCTTGCTCTCGCTGAAAGAATTGTGGTCAGTCTTGCGCTCACTTCGTGTGAACGAATCTGATCCATGAACGTGTCACTGTTCGGTCCTGAGACACACATCCTCGCCGATCTGGAATTATATCACAGGTAGTGAAGGATCCAGTGTGCCTATCAATATTTTCTGGTTACATGCCACTTTATACAGCGGTTCGTACCTTAGGGAATTAGAGAAGGGGTCTTTGTGACTAAGCTGTTTAACGGAGAGTGAGTTTTTTAGTCTCTTTAGATATGAGCGTGGGGACGCAAGCCATAAGTAATTCCCCTCTACAGCGAGGTCAATTTAGGCGGAATATATGGCAGCGGTGCAGAGATAGTGAATGTCACAGATGTGTTATCAGGGATAAGATAGGCAGTCCTTTCACGATCCGCTCGTCCTGAGCTTTGGCCCTGTGGCCGTACATGCGGTCTAGGCCAAGTCTACTCCGGCAAGATACAACATGGGTCAATCGTGTTCACAGCCCGGGTCACATATTCGGGCGACTGGCGTGATACTCGGACCAATTTATAAATGAAGAACAAGACAAATTTTAAGGTACCGCGTGAATTACCATCAGCGAGAATTTCCTAGTGGGCCCCGCGGTTAACGGCCCGATAAATTGGGACAGCGGAGACCGTAGTTCTATACTGCTGCTACGGCCCTAAACACATCCCGCCGAACTGTGGCCACTTCAAATCGGCCATGACGTCCCCGGGTGCCTCTGATCCCGCGTAAGCCAGGGGTGCAGTCACAAATGTAGAATCGATTTCGGGCGGGCCCCACCGACACCTCCGGCCCAAAATTCCCGCGGGACGCTGGTGTCGACACTCCGTTCGCCGGCCTTTACCAGACGAGACCCCCTTGTGAGTTTGGAAACTCAGTTAATTAGTTCTCCTGACTAGAATGTCACATCGTAGCTTATTCACAGTCGCCGGGCGGGTACCAAGAGTCAGCTCTGCTGTTGTACGTATGAACACTGATCGCGACTTCCAGATGCATACAAGAGGGCCCTTCACCTGGAGATGACCCGAGAATGCTCTTAGTACCTCTTTAAAGAGCTTACGGAAATCACAAGATAAATGGGCTCCTCTAGGTCAGGGTGGGTCTCGTTTTAGACACCGCCGGTTTACAGCACATGCTAGAGACTTCCAGTCGACCGGCTTTAGCCCCTTTGAGTTGTCTAGATTGTGAATAACATTGATCACCCGTCGTTCACGACCTTAGTATTGCTGTGGTTCGCGATGCGAACATACGGTGCTTCTTAGGAAACTTCGCTGAGCCCATCCGGCAGTTGACAGTATAAGGGGCGAATTTATCTAAACTATTGAACGATGTTCTCGCTATTGATGTTTGTGTGTAACATCCTACTCGGGATATTACGTCATTTATTGTTCAGCTTCTGAAGACAAACTCTGCAGAGTAAAATGAAGATCCCGGCATCGGTCCGCCGTTATATTCACGACCCTAGAACTTGCCATATGGACGAAACAGATCCACAGAGCCCATTATGTGATATTATTTGTGCATATCGAAGGATTGCGAACTTAATCATAAGATCCAGTAATGGGAAGTTGTATGAACCATTCTTACCGGCGCCGCTCCGAGCTTAATAGCATGACAGCGGCCTACCTACTCGACAAAACTATCATGATGGTAGCTTTCGAAGTCCCGCCTGGCGGGCACTCTAATTAACGCCACTAGTTAATACGGGGGTGCGTCGCACTAAGACATGGCTATCGTTGCTCTGCACGACCTCAAGCAGTCTGGAGCACATCTAAGCGCAAGCTCATTGTGTTGGAGATAATAGGTTGCCTGAATACTACATGTGGCAGCCGCGCACGAGGAGATCATACTCTTACAGGTCGGGATCCAGACTGGTAGTTCCGCTCCGATAAATGATATGCTAGTCAGTAAGCGTGTAGGTAACAGGGAGTCCCTGCGCTGGCCGACGCTCAAATAAGGCAGAACTGCTACGTAGCTTTCCTTCCCGCATATCCCACAGAGTGTCACATGGTTTTTTAAGGTGCTATATGGAGGTTCCAAACTATTCAACAAGGAAGCCCAAGTCCTCAGGGAGTTCTATAGCGATTTACATGCCGACCCGCCCGTAGCAGGACATCCGAATTGATCGCGAGCCCACGCTCGAAGAATTCCACCAATGTAGAAGTAGCCAGAGATACAGGTGCATCTTGCTTGCGAAAAATGAGGCATTTGTCCCAGCGCTCCATGGGTGTTACTTCGACGACAAAGCGTCACCTCTTGTAAGCGCCTACCTCGCTGCCCGCACCGACGATAGTTACCAACTTAGCCGTCGAGACTCGGAGCGGAAGTTTATCCGGCCTGCAACCAAGCCAGAACCAATCGATCAGCCTTCATGATAGACGTGGTCTTAGCAAGATTGCTGCATAAGGTTTAATAAAAGCTTCGTTGCCAAAAGCGATCTACTTGGAGCGTGGATTAAACCCGTCACACACGCGCCAGCATACTAGCAACCCTGATCCGTCTTTACGTGGCATTGGCTGCTTACAAGGAGCCGTTGCATGCGATTCTAGCGATAACAACGACCGACACCGTCGACAATGTCAAATATCACATAGTGGTACGTCGTTGCACCAAGACTTTTAGCGCTCAGCCCCGTTCAATCGATCGCCAGTCAAACCTAGCCCGCTCGCGTGTCCGTACCCAAAATCTTTGTACGTTACCACTAGGTAACAGTTGCTTCGCGGGAGTCTTAGCGTTGCGCAGGGATGAATCTTTGTGCCCTTTACATTCAGGTACACATATTGAGTTCTGATCGGTCCGGGCCGACACTTCTAGGGTGGCGACCGCACGAGAAGAGTATCCAGTCGCTGTGGCATTTTTCCGCGCACTACATGCGTCCCTGGAGCCGTGGCCTAGTGATAGTCAATTGCTCACGATCATTGTACGATGCAGCTTTTGCCGCCATTGACAAAGGTGCACCTAATCTTTAGGAGAGTATTATCTATCCTCCAGTGAGCTCAGGGGAGATAAAACAGGGCCCAACAGGTCTATTGTGTAGCAGACGCACTTCTACGCACAAGTCAAGATCTGTCATTCCGCCCCACTAAGTGGGTAACTATGCCTTAGGCAAGGCGTTCGGAAGGGGCCTTTTAGATCAAGTCGTGGGTTCATCTGGCGGGCGAAGAATGGTTTTAAAAGTCAATATTCAACTTCCAGAAGCCTTACTAAGTCGACGGCTATAATTACTCTGTCTTGTTCGATAGGGGATATGTCCCTCAAAATTAGATTGGACGTCGACTACACTGTCAAAATATAGGAAACGTTAACTAGCGTCGGACATGCTCTGCATTTTTAGTGGGATCCTTTCCATACCCCCGCTCCATCAAGCTTTCGTACTGAGAGAGTATCGCATAATTAACAATAGGTCTCCAGTGAAATAAACTTACGAATTAACATATCACAGCAGATGCCCGTCAAGCAGTAAATCCTCTGCTGGTACAGACGCGCTACAGAAAAGTGTTTCACGACTTTCCTTCTCCTGATTGCCATGCGGCTTTGTGATTCGCACCGCGAACAAGCAAAGTCTGATCGAACTACCACTCTTTTCTTCGCCCTCCTAAGTTGAGATTCGATGCATCCGGAACACTATAGTACTAGAGCGTTTGCCGTCGGTGTAATTGCGCGATGACCGGCCAGTGTCATCGTTGAGGCTATCGTGCATTGGTCAGAAGTCCGGTGGCA')

# 1.3.10
if run(5):
   s = parseSeqsStr('ATGCG GCATG CATGC AGGCA GGCAT GGCAC')
   r = Seq2Graph(s, 'overlap', 0)
   str(r) >> testVs('''GCATG -> CATGC
CATGC -> ATGCG
GGCAT -> GCATG
AGGCA -> GGCAC,GGCAT''')

   s = parseSeqsStr('CT TT TT')
   r = Seq2Graph(s, 'overlap', 0)
   str(r) >> testVs('CT -> TT')

if run(6):
   s = readlines('dataset_198_10.txt')
   r = Seq2Graph(s, 'overlap', 0)
   l = str(r).split('\n')
   l[0] >> testVs('AGTCTGAACTTAGTGCTGCCTCAGA -> GTCTGAACTTAGTGCTGCCTCAGAT')
   l[-1] >> testVs('TGGCAGCAGGCATCTTGGCCAGTAT -> GGCAGCAGGCATCTTGGCCAGTATC')


# 1.4.6 
if run(7):
   r = Seq2Graph(['AAGATTCTCTAAGA'], 'seq', 4)
   str(r) >> testVs('''CTA -> TAA
ATT -> TTC
CTC -> TCT
TTC -> TCT
TAA -> AAG
TCT -> CTC,CTA
AAG -> AGA,AGA
GAT -> ATT
AGA -> GAT''')

   r = Seq2Graph(['GCTTCTTC'], 'seq', 4)
   str(r) >> testVs('''GCT -> CTT
TTC -> TCT
CTT -> TTC,TTC
TCT -> CTT''')

if run(8):
   l = readlines('dataset_199_6.txt')
   r = Seq2Graph([l[1]], 'seq', int(l[0]))
   l = str(r).split('\n')
   l[0] >> testVs('TGACATAACGT -> GACATAACGTT')
   l[-1] >> testVs('GCACGAGCCAG -> CACGAGCCAGA')


# 1.5.8 
if run(9):
   r = Seq2Graph(parseSeqsStr('GAGG CAGG GGGG GGGA CAGG AGGG GGAG'), 'kmer', 0)
   str(r) >> testVs('''CAG -> AGG,AGG
AGG -> GGG
GGA -> GAG
GAG -> AGG
GGG -> GGG,GGA''')

if run(10):
   dna = readlines('dataset_200_8.txt')
   r = Seq2Graph(dna, 'kmer', 0)
   l = str(r).split('\n')
   l[0] >> testVs('AACTATTGGATATCGAAAC -> ACTATTGGATATCGAAACA')
   l[-1] >> testVs('TTTAAACGGCCCGGATGCA -> TTAAACGGCCCGGATGCAG')

if run(1):
   chap1._5_3()
